= Sin Forth
:author: Marcos Cruz (programandala.net)
:revdate: 2023-10-13

// Last modified: 20231013T1757+0200.

// This file is part of Sin Forth
// by Marcos Cruz (programandala.net), 2010/2023.

// This file is in AsciiDoc format (https://asciidoctor.org).

// Description {{{1
== Description

// tag::description[]

Sin Forth is a Forth cross compiler under development, written in
http://forth-standard.org[Forth] with
http://gnu.org/software/gforth[Gforth].

Sin Forth creates machine code programs for any model of
https://en.wikipedia.org/wiki/ZX_Spectrum[ZX Spectrum] or compatible
computer, including the https://specnext.com[ZX Spectrum Next].

// end::description[]

Author's website: <http://programandala.net>.

// Installation {{{1
== Installation

The installation of Sin Forth needs two operations:

1. Make its sources accessible from Gforth.
2. Copy or link the compiler file (src/sin_forth.fs) in a directory
   of the system `PATH`.

=== Sources

There are two methods to make Sin Forth's sources accessible from Gforth:

1. Add the Sin Forth's <src> directory to Gforth's `fpath`. Consult
   Gforth's documentation.

2. Make a symbolic link to Sin Forth's <src> directory in Gforth's
   <site-forth> directory. In a locally compiled Gforth, the command
   on a Linux shell would be the following:
+
----
sudo ln -s SIN_FORTH_PATH/src/ /usr/local/share/gforth/site-forth/sin_forth
----
+
where "SIN_FORTH_PATH" must be replaced with the corresponding path to
Sin Forth's directory on your system.

=== Compiler

In order to make <src/sin_forth.fs> accessible anywhere, you may link
it to any directory in your system `PATH`, removing its filename
extension for convenience:

Example:

----
ln -s SIN_FORTH_PATH/src/sin_forth.fs DIR/sin_forth
----

where "SIN_FORTH_PATH" must be replaced with the corresponding path to
Sin Forth's directory on your system, and "DIR" can be replaced with
`{tilde}/bin` or `{tilde}/.local/bin`.

// Requirements {{{1
== Requirements

- Sin Forth uses some modules of the
  http://programandala.net/en.program.galope.html[Galope library].

- Some modules of Galope need modules of the
  http://irdvo.nl/FFL/[Forth Foundation Library].

- Sin Forth makes the ZX Spectrum .tap files by Metalbrain's
  http://metalbrain.speccy.org/link-eng.htm[bin2tap], which must be
  installed in the system.

// Project directories {{{1
[#_tree]
== Project directories

// tag::tree[]

[horizontal]
``doc``       ::  Manuals in EPUB, HTML and PDF
``src``       ::  Compiler sources
``src/doc``   ::  Documentation sources
``src/lib``   ::  Library sources
``src/test``  ::  Tests sources
``target``    ::  Compiled and disassembled tests
``tmp``       ::  Temporary files created by ``make``

// end::tree[]

// The name {{{1
== The name

Sin Forth is a "sin", because the programs it creates are not _actual_
Forth:

- No dictionary.
- No outer interpreter.
- No inner interpreter: the "compiled" code is a collection of machine
  code subroutines, like in a STC (Subroutine-Threaded Code) Forth.
- No distinction between interpretation and compilation modes in the
  source code of the programs: during the "compilation", parsing and
  "immediate" operations are done by host words, i.e. Gforth words.

Besides, "sin Forth" is the Spanish for "without Forth", which is
another way to describe Sin Forth.

Last, "Sin" is borrowed from "Sinclair".

// History of the repository {{{1
== History of the repository

- 2018-08-19: A Git repository was created from the development
  backups in order to resume the development.
- 2020-12-06: The Git repository was converted to
  http://fossil-scm.org[Fossil].
- 2020-12-18: A http://github.com/programandala.net/sin-forth[GitHub
  mirror] was configured in the Fossil repository.
- 2023-04-05: The repository was converted to
  http://mercurial-scm.org[Mercurial], enabling a better interaction
  with GitHub.
- 2023-10-13: The repository was
  https://hg.sr.ht/~programandala_net/sin_forth[published on
  Sourcehut]; GitHub is kept as a mirror.
