= Sin Forth
:author: Marcos Cruz (programandala.net)
:revdate: 2023-04-05

// Description {{{1
== Description

// tag::description[]

Sin Forth is a Forth cross compiler under development, written in
http://forth-standard.org[Forth] with
http://gnu.org/software/gforth[Gforth].

Sin Forth creates machine code programs for any model of the ZX
Spectrum, ZX Spectrum 128 and compatible computers, including the ZX
Spectrum Next.

// end::description[]

Author's website: <http://programandala.net>.

// Installation {{{1
== Installation

In order to use Sin Forth, its sources must be accessible from Gforth.

One method is to add the Sin Forth's <src> directory to Gforth's
`fpath`. Consult the documentation of Gforth.

A second method is to make a symbolic link to Sin Forth's <src>
directory from Gforth's <site-forth> directory. In a locally compiled
Gforth, the command on a Linux shell would be the following:

----
sudo ln -s ~/YOUR-PATH/src/ /usr/local/share/gforth/site-forth/sin_forth
----

where "YOUR-PATH" must be replaced with the corresponding path to Sin
Forth's <src> directory on your system.

// Requirements {{{1
== Requirements

Sin Forth uses some modules of the
http://programandala.net/en.program.galope.html[Galope library].

Some modules of Galope need modules of the http://irdvo.nl/FFL/[Forth
Foundation Library].

// Project directories {{{1
[#_tree]
== Project directories

// tag::tree[]

[horizontal]
``doc``       ::  Manuals in EPUB, HTML and PDF
``doc/www``   ::  Online documentation for the Fossil repository
``src``       ::  Compiler sources
``src/doc``   ::  Documentation sources
``src/lib``   ::  Library sources
``src/tests`` ::  Tests sources
``target``    ::  Compiled and disassembled tests
``tmp``       ::  Temporary files created by ``make``

// end::tree[]

// History of the repository {{{1
== History of the repository

- 2018-08-19: A Git repository was created from the development
  backups in order to resume the development.
- 2020-12-06: The Git repository was converted to
  http://fossil-scm.org[Fossil].
- 2020-12-18: A http://github.com/programandala.net/sin-forth[GitHub
  mirror] was configured in the Fossil repository.
- 2023-04-05: The repository was converted to
  http://mercurial-scm.org[Mercurial], enabling a better interaction
  with GitHub.
