= Sin Forth to-do list
:author: Marcos Cruz (programandala.net)
:revdate: 2020-12-10

== 2020-12-06

- Update non-standard throw codes 22 in the assembler.
- Update the documentation of the assembler.

== 2020-12-07

- Move `tail-call?` and similar private words to a new word list, e.g.
  `compiler-tools-wordlist`, accesible in a `compiler-definitions` context but
  not in a `target-definitions` context. Or move the public words from
  `compiler-wordlist` to `compiler-wordlist`. For example, also `memory`,
  `t-,`, `initial-target` etc., should not be accesible during the
  compilation of the target, just in case.
- Make the data stack growing direction configurable.
- Add `literal`, `2literal`, `cliteral`, `xliteral`, `sliteral`.
- Make verbosity configurable.  
- Add a compiler `'` to get the target compilation address of a word
  defined by the compiler's `:`.

== 2020-12-08

- Make the configuration directives homogenous and analog, in order to
  prevent name clashes, also with words like `on` and `off`,  when
  they are used inside the target programa.

== 2020-12-09

- Make `memory>` use the `dp` target variable.
- Improve `>z80-label` to replace "-" with "_" or "minus" depending on
  the name.

== 2020-12-10

- Fix: in <Makefile> `bin2tap` needs the execution address, which
  depends on the length of the code. Solution: Create TAP files from
  the BASIC loader (with zmakebas) and from the binary file (with
  bin2code). Then concatenate them.
